/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gaming_setup_low-poly.glb -T 
Files: gaming_setup_low-poly.glb [1.87MB] > C:\Users\thedy\OneDrive\Desktop\3dPortfolio\public\models\gaming_setup_low-poly-transformed.glb [346.64KB] (81%)
Author: LagzDesign (https://sketchfab.com/LagzDesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-setup-low-poly-caffb0d42a594ac2b67970af07d10a5f
Title: Gaming Setup (low-poly)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gaming_setup_low-poly-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={0.349} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} scale={0.349} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.003']} position={[-0.001, 0.933, -0.883]} rotation={[Math.PI / 2, 0, 0]} scale={0.177} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.004']} position={[-0.001, 0.933, -0.883]} rotation={[Math.PI / 2, 0, 0]} scale={0.177} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.005']} position={[-0.001, 0.933, -0.883]} rotation={[Math.PI / 2, 0, 0]} scale={0.177} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.PaletteMaterial002} position={[-0.267, 0.904, -0.347]} rotation={[Math.PI / 2, 0, 0.153]} scale={0.542} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.screen} position={[-0.267, 0.904, -0.347]} rotation={[Math.PI / 2, 0, 0.153]} scale={0.542} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.PaletteMaterial003} position={[-0.267, 0.904, -0.347]} rotation={[Math.PI / 2, 0, 0.153]} scale={0.542} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Material.007']} position={[0.184, 0.908, 0.144]} rotation={[Math.PI / 2, 0, -1.607]} scale={0.273} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.008']} position={[0.184, 0.911, -0.371]} rotation={[Math.PI / 2, 0, -1.405]} scale={0.065} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.PaletteMaterial004} position={[0.16, 0.907, 0]} scale={[0.203, 0.349, 0.64]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.PaletteMaterial005} position={[0.834, 0, -0.127]} rotation={[Math.PI / 2, 0, 2.27]} scale={0.286} />
      <mesh geometry={nodes.Object_29.geometry} material={materials['Material.013']} position={[0.834, 0, -0.127]} rotation={[Math.PI / 2, 0, 2.27]} scale={0.286} />
    </group>
  )
}

useGLTF.preload('/gaming_setup_low-poly-transformed.glb')
