/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/workspace_withRoom.glb 
Author: panggilajablackk (https://sketchfab.com/panggilajablackk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/workspace-by-blackahayy-21eb0d835905483f9b4cf5a8ee3a2812
Title: workspace by blackahayy
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'


type GLTFResult = {
  nodes: {
    window_Mat9_0: THREE.Mesh
    window_Mat1_0: THREE.Mesh
    CD_Mat3_0: THREE.Mesh
    CD_Mat6_0: THREE.Mesh
    CD_Mat9_0: THREE.Mesh
    Mouse_Mat_0: THREE.Mesh
    Mouse_Mat1_0: THREE.Mesh
    Keyboard_Mat14_0: THREE.Mesh
    Keyboard_Mat6_0: THREE.Mesh
    Keyboard_Mat13_0: THREE.Mesh
    Keyboard__0: THREE.Mesh
    Keyboard_Mat1_0: THREE.Mesh
    radio_Mat1_0: THREE.Mesh
    radio_Mat9_0: THREE.Mesh
    radio_Mat_0: THREE.Mesh
    radio_Mat10_0: THREE.Mesh
    laptop_Mat12_0: THREE.Mesh
    laptop_Mat_0: THREE.Mesh
    laptop_Mat9_0: THREE.Mesh
    Book_Mat5_0: THREE.Mesh
    Book_Mat3_0: THREE.Mesh
    Book_Mat10_0: THREE.Mesh
    Book_Mat9_0: THREE.Mesh
    Decor_Light_Mat6_0: THREE.Mesh
    Decor_Light_Mat11_0: THREE.Mesh
    White_board_Mat_0: THREE.Mesh
    White_board_Mat9_0: THREE.Mesh
    CPU_Mat_0: THREE.Mesh
    CPU_Mat1_0: THREE.Mesh
    monitor_Mat12_0: THREE.Mesh
    monitor_Mat1_0: THREE.Mesh
    Chair_Mat4_0: THREE.Mesh
    Chair_Mat1_0: THREE.Mesh
    lemari_Mat1_0: THREE.Mesh
    lemari_Mat8_0: THREE.Mesh
    lemari_Mat_0: THREE.Mesh
    Box_Mat1_0: THREE.Mesh
    Box_Mat5_0: THREE.Mesh
    Tabel_Mat_0: THREE.Mesh
    Tabel_Mat4_0: THREE.Mesh
    Tabel_Mat1_0: THREE.Mesh
    Room_Mat6_0: THREE.Mesh
    Room_Mat7_0: THREE.Mesh
    decor_Mat_0: THREE.Mesh
    keyboard_mat_Mat6_0: THREE.Mesh
  }
  materials: {
    'Mat.9': THREE.MeshStandardMaterial
    'Mat.1': THREE.MeshStandardMaterial
    'Mat.3': THREE.MeshStandardMaterial
    'Mat.6': THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    'Mat.14': THREE.MeshStandardMaterial
    'Mat.13': THREE.MeshStandardMaterial
    Keyboard__0: THREE.MeshStandardMaterial
    'Mat.10': THREE.MeshStandardMaterial
    'Mat.12': THREE.MeshStandardMaterial
    'Mat.5': THREE.MeshStandardMaterial
    'Mat.11': THREE.MeshStandardMaterial
    'Mat.4': THREE.MeshStandardMaterial
    'Mat.8': THREE.MeshStandardMaterial
    'Mat.7': THREE.MeshStandardMaterial
  }
}

type ModelProps = React.ComponentProps<'group'>

export function Model(props: ModelProps) {
  const { nodes, materials } = useGLTF('/workspace_withRoom.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-125.78, 77.228, 0.034]}>
          <mesh geometry={nodes.window_Mat9_0.geometry} material={materials['Mat.9']} />
          <mesh geometry={nodes.window_Mat1_0.geometry} material={materials['Mat.1']} />
        </group>
        <group position={[39.366, 81.223, -97.243]}>
          <mesh geometry={nodes.CD_Mat3_0.geometry} material={materials['Mat.3']} />
          <mesh geometry={nodes.CD_Mat6_0.geometry} material={materials['Mat.6']} />
          <mesh geometry={nodes.CD_Mat9_0.geometry} material={materials['Mat.9']} />
        </group>
        <group position={[-136.2, 69.256, -35.146]}>
          <mesh geometry={nodes.Mouse_Mat_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Mouse_Mat1_0.geometry} material={materials['Mat.1']} />
        </group>
        <group position={[-133.91, 69.517, 0.842]}>
          <mesh geometry={nodes.Keyboard_Mat14_0.geometry} material={materials['Mat.14']} />
          <mesh geometry={nodes.Keyboard_Mat6_0.geometry} material={materials['Mat.6']} />
          <mesh geometry={nodes.Keyboard_Mat13_0.geometry} material={materials['Mat.13']} />
          <mesh geometry={nodes.Keyboard__0.geometry} material={materials.Keyboard__0} />
          <mesh geometry={nodes.Keyboard_Mat1_0.geometry} material={materials['Mat.1']} />
        </group>
        <group position={[75.212, 120.555, -86.563]}>
          <mesh geometry={nodes.radio_Mat1_0.geometry} material={materials['Mat.1']} />
          <mesh geometry={nodes.radio_Mat9_0.geometry} material={materials['Mat.9']} />
          <mesh geometry={nodes.radio_Mat_0.geometry} material={materials.material} />
          <mesh geometry={nodes.radio_Mat10_0.geometry} material={materials['Mat.10']} />
        </group>
        <group position={[-146.235, 75.882, 90.305]}>
          <mesh geometry={nodes.laptop_Mat12_0.geometry} material={materials['Mat.12']} />
          <mesh geometry={nodes.laptop_Mat_0.geometry} material={materials.material} />
          <mesh geometry={nodes.laptop_Mat9_0.geometry} material={materials['Mat.9']} />
        </group>
        <group position={[53.836, 167.24, -100.07]}>
          <mesh geometry={nodes.Book_Mat5_0.geometry} material={materials['Mat.5']} />
          <mesh geometry={nodes.Book_Mat3_0.geometry} material={materials['Mat.3']} />
          <mesh geometry={nodes.Book_Mat10_0.geometry} material={materials['Mat.10']} />
          <mesh geometry={nodes.Book_Mat9_0.geometry} material={materials['Mat.9']} />
        </group>
        <group position={[-90.316, 97.539, 2.31]}>
          <mesh geometry={nodes.Decor_Light_Mat6_0.geometry} material={materials['Mat.6']} />
          <mesh geometry={nodes.Decor_Light_Mat11_0.geometry} material={materials['Mat.11']} />
        </group>
        <group position={[-64.667, 131.308, -144.177]}>
          <mesh geometry={nodes.White_board_Mat_0.geometry} material={materials.material} />
          <mesh geometry={nodes.White_board_Mat9_0.geometry} material={materials['Mat.9']} />
        </group>
        <group position={[-141.148, 94.286, -95.502]}>
          <mesh geometry={nodes.CPU_Mat_0.geometry} material={materials.material} />
          <mesh geometry={nodes.CPU_Mat1_0.geometry} material={materials['Mat.1']} />
        </group>
        <group position={[-165.349, 91.811, -3.366]}>
          <mesh geometry={nodes.monitor_Mat12_0.geometry} material={materials['Mat.12']} />
          <mesh geometry={nodes.monitor_Mat1_0.geometry} material={materials['Mat.1']} />
        </group>
        <group position={[-53.897, 50.373, -3.301]}>
          <mesh geometry={nodes.Chair_Mat4_0.geometry} material={materials['Mat.4']} />
          <mesh geometry={nodes.Chair_Mat1_0.geometry} material={materials['Mat.1']} />
        </group>
        <group position={[49.674, 79.207, -54.958]}>
          <mesh geometry={nodes.lemari_Mat1_0.geometry} material={materials['Mat.1']} />
          <mesh geometry={nodes.lemari_Mat8_0.geometry} material={materials['Mat.8']} />
          <mesh geometry={nodes.lemari_Mat_0.geometry} material={materials.material} />
        </group>
        <group position={[-150.102, 51.338, 125.212]}>
          <mesh geometry={nodes.Box_Mat1_0.geometry} material={materials['Mat.1']} />
          <mesh geometry={nodes.Box_Mat5_0.geometry} material={materials['Mat.5']} />
        </group>
        <group position={[-151.708, 40.634, 12.502]}>
          <mesh geometry={nodes.Tabel_Mat_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Tabel_Mat4_0.geometry} material={materials['Mat.4']} />
          <mesh geometry={nodes.Tabel_Mat1_0.geometry} material={materials['Mat.1']} />
        </group>
        <group position={[-97.432, 60.611, -73.749]}>
          <mesh geometry={nodes.Room_Mat6_0.geometry} material={materials['Mat.6']} />
          <mesh geometry={nodes.Room_Mat7_0.geometry} material={materials['Mat.7']} />
        </group>
        <mesh geometry={nodes.decor_Mat_0.geometry} material={materials.material} position={[-184.784, 131.942, 114.768]} />
        <mesh geometry={nodes.keyboard_mat_Mat6_0.geometry} material={materials['Mat.6']} position={[-135.269, 68.169, -11.796]} />
      </group>
    </group>
  )
}

useGLTF.preload('/workspace_withRoom.glb')